> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy Operations


### 5 Interesting Numpy Operations

**Numpy** is a library for Python programming language which is used for **multi dimentaional array manipulations**. Traditional list operations in Python are slow but **numpy operations** are **50 times faster** and hence it is a very popular library for Data Science and large datsets manipulations. Internally **numpy uses C++** for operations which improves the overall performance.  

We will discuss the below 5 numpy array functions
- **numpy.transpose**
- **numpy.median**
- **numpy.std**
- **numpy.var**
- **numpy.count_nonzero**

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "d-lokesh16/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/d-lokesh16/numpy-array-operations


'https://jovian.ai/d-lokesh16/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.transpose
function2 = np.median
function3 = np.std
function4 = np.var
function5 = np.count_nonzero

## Function 1 - np.transpose

The **np.transpose** function is used to return the **transposed input array**.
<br>Parameters of **np.transpose** function:
- **nparray** as **mandatory parameter**
- **a tuple of axes** as an **optional parameter**
- **returns ndarray**

In [9]:
# Example 1
func1_arr1 = np.array([[1, 2], 
        [3, 4.]])

np.transpose(func1_arr1)

array([[1., 3.],
       [2., 4.]])

The **np.transpose** function takes **nparray func1_arr1 as input** and returns the **transposed nparray**

In [10]:
# Example 2 - working
func1_arr2 = np.ones((2, 3, 1))

np.transpose(func1_arr2, (1, 2, 0))

array([[[1., 1.]],

       [[1., 1.]],

       [[1., 1.]]])

The **np.transpose** function takes **nparray func1_arr2 and the axes in a tuple as inputs** and returns the **transposed nparray**. The axes are re-arranged as per the tuple parameter. 

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
func1_arr3 = [[1, 2], 
        [3, 4.]]

np.transpose(func1_arr3, (1, 2, 0))

ValueError: axes don't match array

The **np.transpose** function takes **nparray func1_arr3 and the axes in a tuple as inputs** and returns the **transposed nparray**. The axes are re-arranged as per the tuple parameter.

The function **breaks** because the **func1_arr3 has only 2 axes** but the **np.transpose has input of 3 axes** in the tuple. Changing the axes **from 3 to 2** will fix this issue. 

**np.transpose** can be used to quickly swap the axes or dimenions of a nparray.

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "d-lokesh16/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/d-lokesh16/numpy-array-operations


'https://jovian.ai/d-lokesh16/numpy-array-operations'

## Function 2 - np.median

**np.median** is a function to **compute median** of the **ndarray**.
<br>Parameters of **np.median** function:
- **nparray** as **mandatory parameter**
- **axis** along which the median should be computed as an **optional parameter**
- **out ndarray** with shape same as input array which can be used to place the result as an **optional parameter**
- **overwrite_input boolean** value to specify if the input has to be overwritten by the output as **optional parameter**
- **returns ndarray**

In [13]:
func2_arr1 = np.array([[10, 7, 4], 
              [3, 2, 1]])

np.median(func2_arr1)

3.5

Since the **np.median** function was not provided with the **axis parameter**, the **default behaviour** is to compute **median along a flattened version of the aaray**.
<br>In that case, the array will be sorted as [1, 2, 3, 4, 7, 10] and the **median is (3 + 4) / 2 = 3.5**

In [14]:
func2_arr2 = np.array([[10, 7, 4], 
              [3, 2, 1]])

np.median(func2_arr2, axis = 1)

array([7., 2.])

Since the **np.median** function was provided with the **axis parameter as 1**, the **median is computed along axis 1 of the aaray**.
<br>In that case, the **median of [4, 7, 10] is 7** and **[1, 2, 3] is 2**

In [15]:
func2_arr3 = np.array([[10, 7, 4], 
              [3, 2, 1]])

np.median(func2_arr3, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

The **np.median** function was provided with the **axis parameter as 2** but the **input array does not have a 3rd axis** and hence the **error**.
<br>The error **can be fixed** by **changing the axis parameter from 2 to either 0 or 1**.

**np.median** is a very quick way to manipulate the median of a large nparray.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "d-lokesh16/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/d-lokesh16/numpy-array-operations


'https://jovian.ai/d-lokesh16/numpy-array-operations'

## Function 3 - np.std

**np.std** is a function to **compute standard deviation** of the **ndarray**.
<br>Parameters of **np.std** function:
- **nparray** as **mandatory parameter**
- **axis** along which the standard deviation should be computed as an **optional parameter**
- **dtype** as the type to compute standard deviation as an **optional parameter**
- **out ndarray** with shape same as input array which can be used to place the result as an **optional parameter**
- **returns ndarray**

In [17]:
func3_arr1 = np.array([[10, 7, 4], 
              [3, 2, 1]])

np.std(func3_arr1)

3.095695936834452

Since the **np.std** function was not provided with the **axis parameter**, the **default behaviour** is to compute **standard deviation along a flattened version of the array**.

In [18]:
func3_arr2 = np.array([[10, 7, 4], 
              [3, 2, 1]])

np.std(func3_arr2, axis = 0)

array([3.5, 2.5, 1.5])

Since the **np.std** function was provided with the **axis parameter as 0**, the **standard variance is computed along axis 1 of the aaray**.

In [19]:
func3_arr3 = np.array([[10, 7, 4], 
              [3, 2, 1]])

np.median(func3_arr3, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

The **np.std** function was provided with the **axis parameter as 2** but the **input array does not have a 3rd axis** and hence the **error**.
<br>The error **can be fixed** by **changing the axis parameter from 2 to either 0 or 1**.

**np.std** is a very quick way to manipulate the standard deviation of a large nparray.

In [20]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "d-lokesh16/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/d-lokesh16/numpy-array-operations


'https://jovian.ai/d-lokesh16/numpy-array-operations'

## Function 4 - np.var

**np.var** is a function to **compute variance** of the **ndarray**.
<br>Parameters of **np.var** function:
- **nparray** as **mandatory parameter**
- **axis** along which the variance should be computed as an **optional parameter**
- **dtype** as the type to compute variance as an **optional parameter**
- **out ndarray** with shape same as input array which can be used to place the result as an **optional parameter**
- **returns ndarray**

In [21]:
func4_arr1 = np.array([[10, 7, 4], 
              [18, 2., 11]])

np.var(func4_arr1)

27.222222222222225

Since the **np.var** function was not provided with the **axis parameter**, the **default behaviour** is to compute **variance along a flattened version of the aaray**.

In [22]:
func4_arr2 = np.array([[10, 7, 4], 
              [18, 2., 11]])

np.var(func4_arr2, axis = 0)

array([16.  ,  6.25, 12.25])

Since the **np.var** function was provided with the **axis parameter as 0**, the **variance is computed along axis 1 of the aaray**.

In [23]:
func4_arr3 = np.array([[10, 7, 4], 
              [18, 2., 11]])

np.var(func4_arr3, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

The **np.var** function was provided with the **axis parameter as 2** but the **input array does not have a 3rd axis** and hence the **error**.
<br>The error **can be fixed** by **changing the axis parameter from 2 to either 0 or 1**.

**np.var** is a very quick way to manipulate the variance of a large nparray.

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "d-lokesh16/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/d-lokesh16/numpy-array-operations


'https://jovian.ai/d-lokesh16/numpy-array-operations'

## Function 5 - np.count_nonzero

**np.count_nonzero** counts the number of non-zero values in the array.
<br>Parameters of **np.count_nonzero** function:
- **nparray** as **mandatory parameter**
- **axis** along which the count should be computed as an **optional parameter**
- **returns count as int**

In [25]:
func5_arr1 = np.array([[10, 7, 4],
                      [8, 12., 0.]])

np.count_nonzero(func5_arr1)

5

Since the **np.count_nonzero** function was not provided with the **axis parameter**, the **default behaviour** is to compute **count along a flattened version of the aaray**.

In [26]:
func5_arr2 = np.array([[10, 7, 4],
                      [8, 12., 0.]])

np.count_nonzero(func5_arr2, axis = 0)

array([2, 2, 1])

Since the **np.count_nonzero** function was provided with the **axis parameter as 0**, the **count is computed along axis 1 of the aaray**.

In [27]:
func5_arr3 = np.array([[10, 7, 4],
                      [8, 12., 0.]])

np.count_nonzero(func5_arr3, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

The **np.count_nonzero** function was provided with the **axis parameter as 2** but the **input array does not have a 3rd axis** and hence the **error**.
<br>The error **can be fixed** by **changing the axis parameter from 2 to either 0 or 1**.

**np.count_nonzero** is a very quick way to manipulate the count of non-zero elements of a large nparray.

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "d-lokesh16/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/d-lokesh16/numpy-array-operations


'https://jovian.ai/d-lokesh16/numpy-array-operations'

## Conclusion

- In this assignment, we have covered 5 numpy functions that can be used in array manipulations and statistics.
- There are so many other important numpy functions which needs to be practiced.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "d-lokesh16/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/d-lokesh16/numpy-array-operations


'https://jovian.ai/d-lokesh16/numpy-array-operations'